//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCAppDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineLogTab
    {
        public int lngId { get; set; }
        public Nullable<int> lngOperatorId { get; set; }
        public string OperatorCode { get; set; }
        public Nullable<int> lngMachineId { get; set; }
        public Nullable<int> MachineNo { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Shift { get; set; }
        public string BatchNo { get; set; }
        public Nullable<int> lngProductId { get; set; }
        public string ProductCode { get; set; }
        public Nullable<decimal> ProductionSetValue { get; set; }
        public Nullable<decimal> ProductionActualValue { get; set; }
        public Nullable<decimal> EfficiencySetValue { get; set; }
        public Nullable<decimal> EfficiencyActualValue { get; set; }
        public Nullable<decimal> UtilizationSetValue { get; set; }
        public Nullable<decimal> UtilizationActualValue { get; set; }
        public Nullable<decimal> LogisticsSetValue { get; set; }
        public Nullable<decimal> LogisticsActualValue { get; set; }
        public Nullable<System.TimeSpan> Batch_StartTime { get; set; }
        public Nullable<System.TimeSpan> Batch_StopTime { get; set; }
        public Nullable<decimal> Total_BatchTime { get; set; }
        public Nullable<bool> blnFinished { get; set; }
        public Nullable<decimal> DayTarget { get; set; }
    
        public virtual tblMasterItem tblMasterItem { get; set; }
    }
}
