//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCAppDataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PPCEntities : DbContext
    {
        public PPCEntities()
            : base("name=PPCEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<lkuSCMLookupData> lkuSCMLookupDatas { get; set; }
        public virtual DbSet<lkuSCMLookupMaster> lkuSCMLookupMasters { get; set; }
        public virtual DbSet<tblCity> tblCities { get; set; }
        public virtual DbSet<tblClient> tblClients { get; set; }
        public virtual DbSet<tblCountry> tblCountries { get; set; }
        public virtual DbSet<tblLocationBinBuffer> tblLocationBinBuffers { get; set; }
        public virtual DbSet<tblLoginInfo> tblLoginInfoes { get; set; }
        public virtual DbSet<tblMasterBin> tblMasterBins { get; set; }
        public virtual DbSet<tblMasterBOMLevel> tblMasterBOMLevels { get; set; }
        public virtual DbSet<tblMasterBOMOperation> tblMasterBOMOperations { get; set; }
        public virtual DbSet<tblMasterCustomer> tblMasterCustomers { get; set; }
        public virtual DbSet<tblMasterCustomerContact> tblMasterCustomerContacts { get; set; }
        public virtual DbSet<tblMasterCustomerSupplierType> tblMasterCustomerSupplierTypes { get; set; }
        public virtual DbSet<tblMasterDesignation> tblMasterDesignations { get; set; }
        public virtual DbSet<tblMasterDocumentType> tblMasterDocumentTypes { get; set; }
        public virtual DbSet<tblMasterDrawing> tblMasterDrawings { get; set; }
        public virtual DbSet<tblMasterItemCategory> tblMasterItemCategories { get; set; }
        public virtual DbSet<tblMasterLocation> tblMasterLocations { get; set; }
        public virtual DbSet<tblMasterLocationContact> tblMasterLocationContacts { get; set; }
        public virtual DbSet<tblMasterTax> tblMasterTaxes { get; set; }
        public virtual DbSet<tblMasterUnitOfMeasure> tblMasterUnitOfMeasures { get; set; }
        public virtual DbSet<tblMaterialRequisition> tblMaterialRequisitions { get; set; }
        public virtual DbSet<tblMaterialRequisitionDetail> tblMaterialRequisitionDetails { get; set; }
        public virtual DbSet<tblMenu> tblMenus { get; set; }
        public virtual DbSet<tblRefreshToken> tblRefreshTokens { get; set; }
        public virtual DbSet<tblRoleMenu> tblRoleMenus { get; set; }
        public virtual DbSet<tblRolePermission> tblRolePermissions { get; set; }
        public virtual DbSet<tblState> tblStates { get; set; }
        public virtual DbSet<tblUserRole> tblUserRoles { get; set; }
        public virtual DbSet<tblMasterVendor> tblMasterVendors { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblPurchaseOrderDeliverySchedule> tblPurchaseOrderDeliverySchedules { get; set; }
        public virtual DbSet<tblDocNumberingPattern> tblDocNumberingPattern { get; set; }
        public virtual DbSet<tblRole> tblRole { get; set; }
        public virtual DbSet<tblTransaction> tblTransaction { get; set; }
        public virtual DbSet<tblProductionPlan> tblProductionPlan { get; set; }
        public virtual DbSet<tblProductionPlanDetails> tblProductionPlanDetails { get; set; }
        public virtual DbSet<tblQCReport> tblQCReport { get; set; }
        public virtual DbSet<tblStoreCredit> tblStoreCredit { get; set; }
        public virtual DbSet<tblMasterItem> tblMasterItems { get; set; }
        public virtual DbSet<tblBillOfMaterial> tblBillOfMaterials { get; set; }
        public virtual DbSet<tblBOMOperation> tblBOMOperations { get; set; }
        public virtual DbSet<tblBillOfMaterialDetail> tblBillOfMaterialDetails { get; set; }
        public virtual DbSet<tblStoreCreditDetails> tblStoreCreditDetails { get; set; }
        public virtual DbSet<tblMaterialReturn> tblMaterialReturn { get; set; }
        public virtual DbSet<tblMaterialReturnDetails> tblMaterialReturnDetails { get; set; }
        public virtual DbSet<tblBatchBuffer> tblBatchBuffer { get; set; }
        public virtual DbSet<tblGoodReciptNote> tblGoodReciptNote { get; set; }
        public virtual DbSet<tblGoodReciptNoteDetail> tblGoodReciptNoteDetail { get; set; }
        public virtual DbSet<tblMachineLog> tblMachineLogs { get; set; }
        public virtual DbSet<tblQuotation> tblQuotations { get; set; }
        public virtual DbSet<tblQuotationDetail> tblQuotationDetails { get; set; }
        public virtual DbSet<tblMailAttachment> tblMailAttachments { get; set; }
        public virtual DbSet<tblMailCommnication> tblMailCommnications { get; set; }
        public virtual DbSet<tblWorkOrder> tblWorkOrders { get; set; }
        public virtual DbSet<tblWorkOrderDetail> tblWorkOrderDetails { get; set; }
        public virtual DbSet<tblMasterSupplier> tblMasterSuppliers { get; set; }
        public virtual DbSet<tblPurchaseOrder> tblPurchaseOrders { get; set; }
        public virtual DbSet<tblPurchaseOrderDetail> tblPurchaseOrderDetails { get; set; }
        public virtual DbSet<tblIndent> tblIndents { get; set; }
        public virtual DbSet<tblIndentItem> tblIndentItems { get; set; }
        public virtual DbSet<tblMasterDepartment> tblMasterDepartments { get; set; }
        public virtual DbSet<MachineLogTab> MachineLogTabs { get; set; }
        public virtual DbSet<tblColorCode> tblColorCodes { get; set; }
        public virtual DbSet<tblMachineMaster> tblMachineMasters { get; set; }
    
        public virtual ObjectResult<spGetItems_Result> spGetItems(Nullable<int> itemId, string filter, string sortOrder)
        {
            var itemIdParameter = itemId.HasValue ?
                new ObjectParameter("ItemId", itemId) :
                new ObjectParameter("ItemId", typeof(int));
    
            var filterParameter = filter != null ?
                new ObjectParameter("Filter", filter) :
                new ObjectParameter("Filter", typeof(string));
    
            var sortOrderParameter = sortOrder != null ?
                new ObjectParameter("SortOrder", sortOrder) :
                new ObjectParameter("SortOrder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetItems_Result>("spGetItems", itemIdParameter, filterParameter, sortOrderParameter);
        }
    
        public virtual ObjectResult<sprocGetSuggestionsToReleaseWorkOrder_Result> sprocGetSuggestionsToReleaseWorkOrder(Nullable<decimal> qty, Nullable<int> itemId)
        {
            var qtyParameter = qty.HasValue ?
                new ObjectParameter("Qty", qty) :
                new ObjectParameter("Qty", typeof(decimal));
    
            var itemIdParameter = itemId.HasValue ?
                new ObjectParameter("ItemId", itemId) :
                new ObjectParameter("ItemId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sprocGetSuggestionsToReleaseWorkOrder_Result>("sprocGetSuggestionsToReleaseWorkOrder", qtyParameter, itemIdParameter);
        }
    
        public virtual ObjectResult<sprocGetQuotationsForPurchaseOrder_Result> sprocGetQuotationsForPurchaseOrder()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sprocGetQuotationsForPurchaseOrder_Result>("sprocGetQuotationsForPurchaseOrder");
        }
    }
}
