//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCAppDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBillOfMaterial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBillOfMaterial()
        {
            this.tblBOMOperations = new HashSet<tblBOMOperation>();
            this.tblBillOfMaterialDetails = new HashSet<tblBillOfMaterialDetail>();
            this.tblWorkOrders = new HashSet<tblWorkOrder>();
        }
    
        public int lngId { get; set; }
        public Nullable<int> lngDocStatus { get; set; }
        public string strBOMNumber { get; set; }
        public Nullable<int> lngItemId { get; set; }
        public string strBOMDescription { get; set; }
        public string strVersion { get; set; }
        public Nullable<decimal> decBatchQty { get; set; }
        public Nullable<int> intDiagramId { get; set; }
        public Nullable<int> intDrawingNo { get; set; }
        public Nullable<int> intLastUpBy { get; set; }
        public Nullable<System.DateTime> datLastUpOn { get; set; }
        public Nullable<int> intCreatedBy { get; set; }
        public Nullable<System.DateTime> datCreatedOn { get; set; }
        public Nullable<bool> boolIsApproved { get; set; }
        public Nullable<int> intApprovedBy { get; set; }
        public Nullable<System.DateTime> datApprovedOn { get; set; }
        public Nullable<bool> boolDelStatus { get; set; }
    
        public virtual tblMasterDrawing tblMasterDrawing { get; set; }
        public virtual tblMasterItem tblMasterItem { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBOMOperation> tblBOMOperations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBillOfMaterialDetail> tblBillOfMaterialDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWorkOrder> tblWorkOrders { get; set; }
    }
}
