//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCAppDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBOMOperation
    {
        public int lngId { get; set; }
        public Nullable<int> lngOperationId { get; set; }
        public Nullable<int> lngBOMId { get; set; }
        public Nullable<decimal> decValue { get; set; }
    
        public virtual tblBillOfMaterial tblBillOfMaterial { get; set; }
        public virtual tblMasterBOMOperation tblMasterBOMOperation { get; set; }
    }
}
