//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCAppDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBatchBuffer
    {
        public int lngId { get; set; }
        public int intGRNDetailId { get; set; }
        public int intLocBinBufferId { get; set; }
        public decimal Buffer { get; set; }
    
        public virtual tblLocationBinBuffer tblLocationBinBuffer { get; set; }
        public virtual tblGoodReciptNoteDetail tblGoodReciptNoteDetail { get; set; }
    }
}
