//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCAppDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblColorCode
    {
        public int lngId { get; set; }
        public Nullable<int> Value { get; set; }
        public string HexCode { get; set; }
        public Nullable<int> ObjId { get; set; }
        public string FontColor { get; set; }
    }
}
