//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCAppDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDocNumberingPattern
    {
        public int lngId { get; set; }
        public int lngMenuId { get; set; }
        public int Length { get; set; }
        public string Prefix { get; set; }
        public string Suffix { get; set; }
        public int Seedvalue { get; set; }
    
        public virtual tblMenu tblMenu { get; set; }
    }
}
