//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCAppDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGoodReciptNoteDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblGoodReciptNoteDetail()
        {
            this.tblBatchBuffer = new HashSet<tblBatchBuffer>();
        }
    
        public int Id { get; set; }
        public int GRNId { get; set; }
        public string strBatchNumber { get; set; }
        public Nullable<System.DateTime> dateExpiryDate { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<decimal> QuantityRecived { get; set; }
        public Nullable<decimal> PricePerUnit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBatchBuffer> tblBatchBuffer { get; set; }
        public virtual tblGoodReciptNote tblGoodReciptNote { get; set; }
        public virtual tblMasterItem tblMasterItem { get; set; }
    }
}
