//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCAppDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIndentItem
    {
        public int lngId { get; set; }
        public Nullable<int> lngIndentId { get; set; }
        public Nullable<int> lngItemId { get; set; }
        public Nullable<decimal> intQty { get; set; }
        public Nullable<decimal> intPOQty { get; set; }
        public Nullable<decimal> intReceivedQty { get; set; }
        public string strNote { get; set; }
        public Nullable<System.DateTime> datExpected { get; set; }
        public Nullable<decimal> intprovisionalPOQuantity { get; set; }
    
        public virtual tblIndent tblIndent { get; set; }
        public virtual tblMasterItem tblMasterItem { get; set; }
    }
}
