//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCAppDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLocationBinBuffer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLocationBinBuffer()
        {
            this.tblTransaction = new HashSet<tblTransaction>();
            this.tblBatchBuffer = new HashSet<tblBatchBuffer>();
        }
    
        public int lngId { get; set; }
        public Nullable<int> lngLocationId { get; set; }
        public Nullable<int> lngBinId { get; set; }
        public Nullable<int> lngItemId { get; set; }
        public Nullable<decimal> Buffer { get; set; }
    
        public virtual tblMasterBin tblMasterBin { get; set; }
        public virtual tblMasterLocation tblMasterLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTransaction> tblTransaction { get; set; }
        public virtual tblMasterItem tblMasterItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBatchBuffer> tblBatchBuffer { get; set; }
    }
}
