//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCAppDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoginInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLoginInfo()
        {
            this.tblUserRoles = new HashSet<tblUserRole>();
        }
    
        public int LoginId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string LoginName { get; set; }
        public Nullable<bool> IsEmailVerified { get; set; }
        public Nullable<System.DateTime> LastLoginOn { get; set; }
        public Nullable<int> LoginFailedAttempt { get; set; }
        public string CreatedIP { get; set; }
        public string LastLoginIP { get; set; }
        public Nullable<System.DateTime> PasswordLastUpdated { get; set; }
        public Nullable<bool> IsBlock { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> DelStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserRole> tblUserRoles { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
