//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCAppDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMachineLog
    {
        public int lngID { get; set; }
        public string strMachineName { get; set; }
        public Nullable<bool> blnStatus { get; set; }
        public Nullable<decimal> decSetTemp { get; set; }
        public Nullable<decimal> decCurrentTemp { get; set; }
        public Nullable<decimal> decFlowGPM { get; set; }
        public Nullable<decimal> decCurrentKWUsage { get; set; }
        public Nullable<System.DateTime> datOperationDate { get; set; }
    }
}
