//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCAppDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMasterCustomerContact
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public string Phone { get; set; }
        public string Mobile1 { get; set; }
        public string Mobile2 { get; set; }
        public string Email { get; set; }
        public Nullable<int> Department { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<int> CustomerId { get; set; }
    
        public virtual tblMasterCustomer tblMasterCustomer { get; set; }
        public virtual tblMasterDepartment tblMasterDepartment { get; set; }
    }
}
