//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCAppDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMasterItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMasterItem()
        {
            this.tblLocationBinBuffers = new HashSet<tblLocationBinBuffer>();
            this.tblMasterDrawings = new HashSet<tblMasterDrawing>();
            this.tblMaterialRequisitionDetails = new HashSet<tblMaterialRequisitionDetail>();
            this.tblProductionPlanDetails = new HashSet<tblProductionPlanDetails>();
            this.tblTransactions = new HashSet<tblTransaction>();
            this.tblBillOfMaterialDetails = new HashSet<tblBillOfMaterialDetail>();
            this.tblStoreCreditDetails = new HashSet<tblStoreCreditDetails>();
            this.tblMaterialReturnDetails = new HashSet<tblMaterialReturnDetails>();
            this.tblGoodReciptNoteDetail = new HashSet<tblGoodReciptNoteDetail>();
            this.tblQuotationDetails = new HashSet<tblQuotationDetail>();
            this.tblWorkOrders = new HashSet<tblWorkOrder>();
            this.tblWorkOrderDetails = new HashSet<tblWorkOrderDetail>();
            this.tblPurchaseOrderDetails = new HashSet<tblPurchaseOrderDetail>();
            this.tblIndentItems = new HashSet<tblIndentItem>();
            this.MachineLogTabs = new HashSet<MachineLogTab>();
        }
    
        public int Id { get; set; }
        public string Identifier { get; set; }
        public string PartNumber { get; set; }
        public string ItemName { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<int> ItemCategory { get; set; }
        public Nullable<decimal> MinStockLevel { get; set; }
        public Nullable<decimal> MaxStockLevel { get; set; }
        public Nullable<int> UOM { get; set; }
        public Nullable<decimal> Reprocurement { get; set; }
        public Nullable<decimal> LeadTime { get; set; }
        public string LeadTimeUnit { get; set; }
        public Nullable<decimal> Buffer { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<int> LastUpBy { get; set; }
        public Nullable<System.DateTime> LastUpOn { get; set; }
        public Nullable<bool> DelStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLocationBinBuffer> tblLocationBinBuffers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMasterDrawing> tblMasterDrawings { get; set; }
        public virtual tblMasterItemCategory tblMasterItemCategory { get; set; }
        public virtual tblMasterUnitOfMeasure tblMasterUnitOfMeasure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMaterialRequisitionDetail> tblMaterialRequisitionDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductionPlanDetails> tblProductionPlanDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTransaction> tblTransactions { get; set; }
        public virtual tblBillOfMaterial tblBillOfMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBillOfMaterialDetail> tblBillOfMaterialDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStoreCreditDetails> tblStoreCreditDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMaterialReturnDetails> tblMaterialReturnDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGoodReciptNoteDetail> tblGoodReciptNoteDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuotationDetail> tblQuotationDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWorkOrder> tblWorkOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWorkOrderDetail> tblWorkOrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseOrderDetail> tblPurchaseOrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblIndentItem> tblIndentItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MachineLogTab> MachineLogTabs { get; set; }
    }
}
