//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCAppDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMasterDrawing
    {
        public int Id { get; set; }
        public string Identifier { get; set; }
        public string Version { get; set; }
        public string Description { get; set; }
        public byte[] Drawing { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> AddedBY { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<int> LastUpBy { get; set; }
        public Nullable<System.DateTime> LastUpOn { get; set; }
        public Nullable<bool> DelStatus { get; set; }
    
        public virtual tblMasterItem tblMasterItem { get; set; }
        public virtual tblBillOfMaterial tblBillOfMaterial { get; set; }
    }
}
