//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCAppDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMachineMaster
    {
        public int lngId { get; set; }
        public string strMachineNo { get; set; }
        public string strMachineName { get; set; }
        public Nullable<bool> blnActive { get; set; }
    }
}
