//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCAppDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMaterialRequisition
    {
        public int lngId { get; set; }
        public int lngDocStatus { get; set; }
        public int lngDepartmentId { get; set; }
        public string strDocumentNumber { get; set; }
        public System.DateTime datDocumentDate { get; set; }
        public int lngCreatedBy { get; set; }
        public System.DateTime datCreatedDate { get; set; }
        public Nullable<int> lngApprovedBy { get; set; }
        public Nullable<System.DateTime> datApprovedDate { get; set; }
        public string strNote { get; set; }
        public bool blnDeleted { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        public virtual tblMasterDepartment tblMasterDepartment { get; set; }
    }
}
