//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCAppDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMailCommnication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMailCommnication()
        {
            this.tblMailAttachments = new HashSet<tblMailAttachment>();
        }
    
        public int lngId { get; set; }
        public Nullable<int> lngUserId { get; set; }
        public Nullable<int> lngMailTOFrom { get; set; }
        public Nullable<int> lngCC { get; set; }
        public Nullable<int> lngBCC { get; set; }
        public string strMailSubject { get; set; }
        public string strMailBody { get; set; }
        public Nullable<int> intMailFolder { get; set; }
        public Nullable<System.DateTime> datAddedOn { get; set; }
        public Nullable<bool> boolIsRead { get; set; }
        public Nullable<bool> boolDelStatus { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMailAttachment> tblMailAttachments { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        public virtual tblUser tblUser2 { get; set; }
        public virtual tblUser tblUser3 { get; set; }
    }
}
