//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCAppDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPurchaseOrderDetail
    {
        public int lngId { get; set; }
        public int lngPOId { get; set; }
        public int lngItemId { get; set; }
        public decimal OrderQty { get; set; }
        public decimal Rate { get; set; }
        public decimal Tax { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> lngQuoteId_Ref { get; set; }
        public Nullable<int> lngContractId_Ref { get; set; }
        public Nullable<int> lngPOId_Ref { get; set; }
        public string strNote { get; set; }
        public System.DateTime datExpectedDate { get; set; }
        public Nullable<int> lngDeliverySchedule { get; set; }
        public Nullable<int> lngIndentId { get; set; }
    
        public virtual tblMasterItem tblMasterItem { get; set; }
        public virtual tblPurchaseOrder tblPurchaseOrder { get; set; }
        public virtual tblIndent tblIndent { get; set; }
    }
}
