//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCAppDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductionPlanDetails
    {
        public int lngId { get; set; }
        public int lngProdPlanId { get; set; }
        public int lngItemId { get; set; }
        public decimal Qty { get; set; }
        public decimal Days { get; set; }
        public System.DateTime datStartDate { get; set; }
        public System.DateTime datEndDate { get; set; }
        public string strNote { get; set; }
    
        public virtual tblProductionPlan tblProductionPlan { get; set; }
        public virtual tblMasterItem tblMasterItem { get; set; }
    }
}
