//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCAppDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPurchaseOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPurchaseOrder()
        {
            this.tblPurchaseOrderDetails = new HashSet<tblPurchaseOrderDetail>();
        }
    
        public int lngId { get; set; }
        public int lngDocStatus { get; set; }
        public Nullable<int> lngQuoteId { get; set; }
        public Nullable<int> lngContractId { get; set; }
        public int lngSupplierId { get; set; }
        public string strPONumber { get; set; }
        public System.DateTime datPODate { get; set; }
        public string strNote { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> Freight { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> OtherAmount { get; set; }
        public string OtherAmountSpecify { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public int lngCreatedBy { get; set; }
        public System.DateTime datCreatedDate { get; set; }
        public Nullable<int> lngApprovedBy { get; set; }
        public Nullable<System.DateTime> datApprovedBy { get; set; }
        public int lngPurchaseStatus { get; set; }
        public bool blnDeleted { get; set; }
        public Nullable<int> lngLastUpBy { get; set; }
        public Nullable<System.DateTime> datLastUpOn { get; set; }
        public string TransactionId { get; set; }
    
        public virtual tblMasterSupplier tblMasterSupplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseOrderDetail> tblPurchaseOrderDetails { get; set; }
    }
}
