//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCAppDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductionPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProductionPlan()
        {
            this.tblProductionPlanDetails = new HashSet<tblProductionPlanDetails>();
        }
    
        public int lngId { get; set; }
        public int lngDocStatus { get; set; }
        public Nullable<int> lngSalesPlan { get; set; }
        public string strProdPlanNumber { get; set; }
        public System.DateTime datProdPlanDate { get; set; }
        public Nullable<System.DateTime> datPlanStartDate { get; set; }
        public Nullable<System.DateTime> datPlanEndDate { get; set; }
        public int lngCreatedBy { get; set; }
        public Nullable<System.DateTime> datCreatedDate { get; set; }
        public int lngApprovedBy { get; set; }
        public Nullable<System.DateTime> datApprovedDate { get; set; }
        public bool blnDeleted { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductionPlanDetails> tblProductionPlanDetails { get; set; }
    }
}
