//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCAppDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQCReport
    {
        public int lngId { get; set; }
        public int lngDocStatus { get; set; }
        public string strQCReportNumber { get; set; }
        public System.DateTime datQCReportDate { get; set; }
        public int lngWorkOrderId { get; set; }
        public decimal QtyReceivedForQC { get; set; }
        public Nullable<decimal> QtyRejected { get; set; }
        public Nullable<decimal> QtyPassed { get; set; }
        public string strQCReportNote { get; set; }
        public int lngCreatedBy { get; set; }
        public System.DateTime datCreatedDate { get; set; }
        public Nullable<int> lngApprovedBy { get; set; }
        public Nullable<System.DateTime> datApprovedBy { get; set; }
        public Nullable<bool> blnDeleted { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        public virtual tblWorkOrder tblWorkOrder { get; set; }
    }
}
