//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCAppDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRolePermission
    {
        public int Id { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<bool> IsAddEdit { get; set; }
        public Nullable<bool> IsView { get; set; }
    
        public virtual tblRole tblRole { get; set; }
    }
}
