//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCAppDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStoreCreditDetails
    {
        public int lngId { get; set; }
        public int lngStoreCreditId { get; set; }
        public int lngWorkOrderId { get; set; }
        public int lngItemId { get; set; }
        public decimal Qty { get; set; }
        public int lngBinId { get; set; }
        public string strNote { get; set; }
    
        public virtual tblMasterBin tblMasterBin { get; set; }
        public virtual tblMasterItem tblMasterItem { get; set; }
        public virtual tblStoreCredit tblStoreCredit { get; set; }
        public virtual tblWorkOrder tblWorkOrder { get; set; }
    }
}
