//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCAppDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransaction
    {
        public int lngId { get; set; }
        public int lngDocumentId { get; set; }
        public int lngDocType { get; set; }
        public string strDocumentNumber { get; set; }
        public System.DateTime datDocumentDate { get; set; }
        public int lngItemId { get; set; }
        public decimal Qty { get; set; }
        public Nullable<int> lngLocationBinBufferId { get; set; }
    
        public virtual tblLocationBinBuffer tblLocationBinBuffer { get; set; }
        public virtual tblMaterialRequisitionDetail tblMaterialRequisitionDetail { get; set; }
        public virtual tblMasterItem tblMasterItem { get; set; }
    }
}
