//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCAppDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkOrderDetail
    {
        public int lngId { get; set; }
        public Nullable<int> lngWOId { get; set; }
        public Nullable<int> lngItemId { get; set; }
        public Nullable<decimal> lngQuantity { get; set; }
        public string intPhase { get; set; }
        public string strNote { get; set; }
        public Nullable<decimal> decIssuedQty { get; set; }
    
        public virtual tblMasterItem tblMasterItem { get; set; }
        public virtual tblWorkOrder tblWorkOrder { get; set; }
    }
}
