//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCAppDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblWorkOrder()
        {
            this.tblMaterialRequisitionDetails = new HashSet<tblMaterialRequisitionDetail>();
            this.tblMaterialReturnDetails = new HashSet<tblMaterialReturnDetails>();
            this.tblQCReports = new HashSet<tblQCReport>();
            this.tblStoreCreditDetails = new HashSet<tblStoreCreditDetails>();
            this.tblWorkOrderDetails = new HashSet<tblWorkOrderDetail>();
        }
    
        public int lngId { get; set; }
        public Nullable<int> lngItemId { get; set; }
        public string strWONumber { get; set; }
        public Nullable<System.DateTime> datExpectedDateOfCompletation { get; set; }
        public Nullable<decimal> decBatchQty { get; set; }
        public Nullable<int> intDepartmentId { get; set; }
        public Nullable<int> intBOMId { get; set; }
        public Nullable<int> intProductionPlanId { get; set; }
        public Nullable<int> intSalesForecastId { get; set; }
        public Nullable<int> intCustomerOrderId { get; set; }
        public string strWODescription { get; set; }
        public Nullable<int> intCreatedBy { get; set; }
        public Nullable<System.DateTime> datCreatedDate { get; set; }
        public Nullable<int> intApprovedBy { get; set; }
        public Nullable<System.DateTime> datApprovedDate { get; set; }
        public Nullable<int> intAssignedTo { get; set; }
        public Nullable<System.DateTime> datAssignedDate { get; set; }
        public Nullable<int> intLastUpBy { get; set; }
        public Nullable<System.DateTime> datLastUpOn { get; set; }
        public Nullable<bool> boolDelStatus { get; set; }
        public Nullable<int> lngDocStatus { get; set; }
    
        public virtual tblBillOfMaterial tblBillOfMaterial { get; set; }
        public virtual tblMasterItem tblMasterItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMaterialRequisitionDetail> tblMaterialRequisitionDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMaterialReturnDetails> tblMaterialReturnDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQCReport> tblQCReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStoreCreditDetails> tblStoreCreditDetails { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        public virtual tblUser tblUser2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWorkOrderDetail> tblWorkOrderDetails { get; set; }
        public virtual tblMasterDepartment tblMasterDepartment { get; set; }
    }
}
